### ISSUE TITLE
e2e demo

### ISSUE THREAD

**Issue by lintool** [salman1993/simple-qa-on-kb#10]
I'd like to see a complete e2e demo where I can type in a textual question 'when was albert einstein born' and get back the answer 'March 14, 1879', showing intermediate results along the way (entity detection, entity linking, relation prediction).

Ideally I'd like this all wrapped up in a REST endpoint, but I'm open to discussion.

This is blocked by #3 

@aliceranzhou can you please take the lead on this? Coordinate w/ @salman1993 re: #2 to help you out.

**Comment by aliceranzhou** [comment]
Sounds good, will do.

**Comment by lintool** [comment]
Hrmm... it seems like we still don't have an end-to-end demo?

**Comment by nlpjoe** [comment]
Hey, you are doing a restful server right now?  alice-api-code seems like to do that, but the app.py can't run:
```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from server import Server
  File "/home/jzzhou/gitlab/BuboQA/alice-api-code/server.py", line 13, in <module>
    from entity_detection.simple_qa_ner import SimpleQADataset
ModuleNotFoundError: No module named 'entity_detection'
```
and the last commit is about 8 mouth ago...

**Comment by binjiaqm** [comment]
Have the same issue with nlpjoe. The server cannot start.

**Comment by lintool** [comment]
@binjiaqm @nlpjoe Unfortunately, the e2e server is broken... @aliceranzhou is graduating and @Impavidity is away at an internship for the summer, so it is unclear when we're going to have this working again...

However, code contributions are welcome!
